'use client';
import './globals.css';
import { Inter } from 'next/font/google';
import { ConfigProvider, theme } from 'antd';
import { ReactFlowProvider } from 'reactflow';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <ReactFlowProvider>
        <ConfigProvider
          theme={{
            algorithm: theme.darkAlgorithm,
          }}
        >
          <body className='p-5'>{children}</body>
        </ConfigProvider>
      </ReactFlowProvider>
    </html>
  );
}
